version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  commit-message:
    prefix: "chore"
    include: "scope"  
  open-pull-requests-limit: 10
  ignore:
    # cross-fetch and node-fetch must be synced manually
    - dependency_name: "cross-fetch"
    - dependency_name: "node-fetch"
    - dependency_name: "release-it"
    - dependency_name: "@release-it/conventional-changelog"
